name: learn-github-actions
on: [push]
jobs:
  action1:
    runs-on: ubuntu-latest
    steps:
      - name: prep
        uses: t0ster/gh-action@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ steps.prep.outputs.branch }}-${{ steps.prep.outputs.shortsha }}"
