name: build-and-push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: prep
        uses: t0ster/gh-action@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: t0ster/actions-cache@master
        with:
          path: |
            /tmp/.buildx-cache
            /tmp/.buildx-cache-test
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # - name: View cache
      #   run: du -h /tmp/.buildx-cache && ls -la /tmp/.buildx-cache/blobs/sha256
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build for Test
        uses: docker/build-push-action@v2
        with:
          tags: t0ster/kuber-ui:test
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            type=local,src=/tmp/.buildx-cache-test
          # For some reason for proper caching we need separate cache for test image
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-test
          load: true
          target: stage-test
      - name: Run Tests
        run: docker run --rm -e JEST_JUNIT_OUTPUT_DIR=/test-results -v $(pwd):/test-results t0ster/kuber-ui:test
      - name: Publish Tests
        uses: IgnusG/jest-report-action@v2.3.3
        if: always() # Or use "continue-on-error: true" in previous test step
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: t0ster/kuber-ui:${{ steps.prep.outputs.branch }}.${{ steps.prep.outputs.shortsha }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            type=local,src=/tmp/.buildx-cache-test
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
# 16
